spring.application.name=recipieServer
spring.datasource.url=jdbc:postgresql://localhost:5432/recipes_db
spring.datasource.username=recipe
spring.datasource.password=Jefino@1537
spring.jpa.hibernate.ddl-auto=validate
server.port=8081
spring.jpa.show-sql=false
